name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Because...'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea

      - name: 'Set up version string'
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION="1-ea+${SHA7}"
          echo "VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: 'Build with Bach'
        uses: sormuras/bach-build@main
        with:
          bach-version: ea
          project-version: ${{ env.VERSION }}
          project-java-release: 9

      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ env.VERSION }}
          path: |
            .bach/workspace/modules

      - name: 'Rename modular JAR files to match early-access tag'
        run: |
          ls .bach/workspace/modules
          for i in .bach/workspace/modules/*.jar; do mv "$i" "${i/${{ env.VERSION }}/early-access}"; done
          ls .bach/workspace/modules

      - name: 'Release early-access build'
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 'early-access'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "Sawdust ${{ env.VERSION }}"
          files: |
            .bach/workspace/modules/*.jar
