name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Because...'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea

      - name: 'Set up version string'
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION="1-ea+${SHA7}"
          echo "VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: 'Initialize Bach'
        run: jshell https://bit.ly/bach-init

      - name: 'Build with Bach'
        run: .bach/bin/bach --guess --project-version ${{ env.VERSION }} --project-targets-java 9 build

      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ env.VERSION }}
          path: |
            .bach/workspace/modules

      - name: 'Release early-access build'
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 'early-access'
          prerelease: true
          name: "Sawdust ${{ env.VERSION }}"
          body: "Release of Sawdust ${{ env.VERSION }}"
          files: |
            .bach/workspace/modules/*.jar
