name: Release

on:
  release:
    types: [ published ]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea

      - name: 'Build with Bach'
        uses: sormuras/bach-build@v1
        with:
          bach-version: 16
          project-version: ${{ github.event.release.tag_name }}
          project-main-release: 9

      - name: 'Upload module com.github.sormuras.sawdust'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .bach/workspace/modules/com.github.sormuras.sawdust@${{ github.event.release.tag_name }}.jar
          asset_name: com.github.sormuras.sawdust@${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive

      - name: 'Upload module com.github.sormuras.sawdust.api'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .bach/workspace/modules/com.github.sormuras.sawdust.api@${{ github.event.release.tag_name }}.jar
          asset_name: com.github.sormuras.sawdust.api@${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive

      - name: 'Upload module com.github.sormuras.sawdust.core'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .bach/workspace/modules/com.github.sormuras.sawdust.core@${{ github.event.release.tag_name }}.jar
          asset_name: com.github.sormuras.sawdust.core@${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
