name: Release

on:
  release:
    types: [ published ]

env:
  GITHUB_TOKEN: ${{ github.token }}
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea

      - name: 'Initialize Bach'
        run: jshell https://bit.ly/bach-init

      - name: 'Build with Bach'
        run: .bach/bin/bach --guess --project-version $VERSION --project-targets-java 9 build

      - name: 'Upload modules'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: ${{ env.VERSION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: "Sawdust ${{ env.VERSION }}"
          files: .bach/workspace/modules/*.jar
