name: Release

on:
  workflow_dispatch:
    inputs:
      tag-version:
        description: 'Tag as version'
        required: true
        default: '1-ea'
      pre-release:
        description: 'Pre-release? [true|false]'
        required: true
        default: 'true'

env:
  VERSION: ${{ github.event.inputs.tag-version }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: 'Initialize Bach'
        run: jshell https://bit.ly/bach-init

      - name: 'Build with Bach'
        run: .bach/bin/bach --guess --project-version ${{ env.VERSION }} --project-targets-java 9 build

      - name: 'Release ${{ env.VERSION }}'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: ${{ env.VERSION }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.event.inputs.pre-release }}
          title: "Sawdust ${{ env.VERSION }}"
          files: .bach/workspace/modules/*.jar
